
/* Drop Tables */

DROP TABLE MW.TAGGED_MATERIAL;
DROP TABLE MW.MATERIAL;




/* Create Tables */

CREATE TABLE MW.TAGGED_MATERIAL
(
	MATERIAL_ID CHAR(14) NOT NULL UNIQUE,
	TAG CHAR(8) NOT NULL UNIQUE,
	MEMO VARCHAR(256),
	TAG_STATE CHAR,
	PRIMARY KEY (MATERIAL_ID, TAG),
	UNIQUE (MATERIAL_ID, TAG)
);


CREATE TABLE MW.MATERIAL
(
	MATERIAL_ID CHAR(14) NOT NULL,
	CREATED_YEAR INTEGER NOT NULL,
	CREATED_MONTH INTEGER NOT NULL,
	MATERIAL_TYPE CHAR(1) NOT NULL,
	MATERIAL_STATE CHAR NOT NULL,
	PRIMARY KEY (MATERIAL_ID)
);



/* Create Foreign Keys */

ALTER TABLE MW.TAGGED_MATERIAL
	ADD FOREIGN KEY (MATERIAL_ID)
	REFERENCES MW.MATERIAL (MATERIAL_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



